<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestTimeFunctions-20190514191645" tests="16" time="3.437">
	<testcase classname="TestTimeFunctions" name="test_ISO8601_Local__symmetric" time="1.591"/>
	<testcase classname="TestTimeFunctions" name="test_extract_is_o8601__local" time="0.003"/>
	<testcase classname="TestTimeFunctions" name="test_extract_is_o8601__ut_c" time="0.073"/>
	<testcase classname="TestTimeFunctions" name="test_extract_rf_c2822__local" time="0.084"/>
	<testcase classname="TestTimeFunctions" name="test_extract_rf_c2822__ut_c" time="0.086"/>
	<testcase classname="TestTimeFunctions" name="test_extract_seconds" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_human" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_is_o8601__local" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_is_o8601__ut_c" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_rf_c2822__local" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_rf_c2822__ut_c" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_seconds" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_t_zval" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_get_time_in_format" time="0.001"/>
	<testcase classname="TestTimeFunctions" name="test_rf_c2822_local_symmetric" time="1.470"/>
	<testcase classname="TestTimeFunctions" name="test_extract_human" time="0.121">
		<error message="1518767040 != 1518745440.0" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "./test_lib_timeConversion.py", line 61, in test_extract_human
    self.assertEqual(now, extractHuman(human))
AssertionError: 1518767040 != 1518745440.0
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
